In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("cursos-prouni.csv")

In [3]:
df.head()

,uf_busca,cidade_busca,universidade_nome,campus_nome,nome,grau,turno,mensalidade,bolsa_integral_cotas,bolsa_integral_ampla,bolsa_parcial_cotas,bolsa_parcial_ampla,nota_integral_ampla,nota_integral_cotas,nota_parcial_ampla,nota_parcial_cotas
0,AC,Acrelandia,Universidade Paulista - UNIP,ACRELANDIA - Centro,Administração,Bacharelado,Curso a Distância,289.0,1.0,1.0,NaN,NaN,572.74,548.0,NaN,NaN
1,AC,Cruzeiro do Sul,Centro Universitário Internacional - Uninter -...,PAP CRUZEIRO DO SUL - Centro,Administração,Bacharelado,Curso a Distância,298.0,1.0,NaN,NaN,NaN,646.14,NaN,NaN,NaN
2,AC,Cruzeiro do Sul,Faculdade Educacional da Lapa - FAEL,AC - CRUZEIRO DO SUL - POLO EAD - CENTRO,Administração,Bacharelado,Curso a Distância,325.0,NaN,NaN,1.0,NaN,NaN,NaN,577.62,NaN
3,AC,Cruzeiro do Sul,Universidade Paulista - UNIP,CRUZEIRO DO SUL - Centro,Administração,Bacharelado,Curso a Distância,319.0,1.0,NaN,NaN,NaN,616.68,NaN,NaN,NaN
4,AC,Rio Branco,Centro Universitário Internacional - Uninter -...,PAP RIO BRANCO - Bosque,Administração,Bacharelado,Curso a Distância,298.0,NaN,NaN,1.0,NaN,NaN,NaN,569.00,NaN

In [4]:
for i, v in enumerate(df.columns):
    print(i, v)

0 uf_busca
1 cidade_busca
2 universidade_nome
3 campus_nome
4 nome
5 grau
6 turno
7 mensalidade
8 bolsa_integral_cotas
9 bolsa_integral_ampla
10 bolsa_parcial_cotas
11 bolsa_parcial_ampla
12 nota_integral_ampla
13 nota_integral_cotas
14 nota_parcial_ampla
15 nota_parcial_cotas

In [5]:
df[df.nome == "Administração"].describe()

,mensalidade,bolsa_integral_cotas,bolsa_integral_ampla,bolsa_parcial_cotas,bolsa_parcial_ampla,nota_integral_ampla,nota_integral_cotas,nota_parcial_ampla,nota_parcial_cotas
count,2754.000000,2288.000000,1799.000000,570.000000,867.000000,2288.000000,1302.000000,1056.000000,381.000000
mean,542.997491,1.774038,2.876598,2.096491,11.916955,575.236670,554.266651,533.483580,510.981995
std,392.767032,2.473487,4.184736,2.020846,25.640435,42.079418,48.546789,51.418042,48.777326
min,169.000000,0.000000,1.000000,1.000000,1.000000,450.000000,450.000000,450.000000,450.000000
25%,298.000000,1.000000,1.000000,1.000000,1.000000,553.750000,530.050000,497.825000,450.000000
50%,393.675000,1.000000,2.000000,1.000000,3.000000,578.220000,563.100000,542.140000,513.240000
75%,694.772500,2.000000,3.000000,2.000000,10.000000,601.925000,588.185000,571.180000,552.980000
max,6552.520000,37.000000,67.000000,15.000000,350.000000,729.040000,675.560000,682.360000,655.320000

In [4]:
df[df.nome == "Administração"].groupby("uf_busca").describe()

         bolsa_integral_ampla                                                 \
                        count      mean       std  min  25%  50%   75%   max
uf_busca
AC                        5.0  1.200000  0.447214  1.0  1.0  1.0  1.00   2.0
AL                       15.0  1.866667  1.187234  1.0  1.0  1.0  2.50   5.0
AM                       13.0  1.692308  1.931520  1.0  1.0  1.0  1.00   8.0
AP                        6.0  1.833333  0.983192  1.0  1.0  1.5  2.75   3.0
BA                       65.0  2.153846  3.083377  1.0  1.0  1.0  2.00  16.0
CE                       45.0  1.600000  1.498484  1.0  1.0  1.0  2.00  10.0
DF                       30.0  1.933333  1.529781  1.0  1.0  1.0  2.00   6.0
ES                       32.0  2.156250  1.461536  1.0  1.0  2.0  3.00   6.0
GO                       57.0  2.122807  1.881016  1.0  1.0  1.0  3.00  10.0
MA                       21.0  1.857143  2.080522  1.0  1.0  1.0  1.00  10.0
MG                      159.0  2.408805  1.627353  1.0  1.0  2.0  3.00   9.0
MS                       37.0  1.540541  0.730091  1.0  1.0  1.0  2.00   3.0
MT                       28.0  1.571429  0.878912  1.0  1.0  1.0  2.00   4.0
PA                       28.0  2.214286  1.750283  1.0  1.0  2.0  2.00   7.0
PB                       28.0  2.250000  2.187930  1.0  1.0  2.0  2.00  12.0
PE                       61.0  3.131148  3.495118  1.0  1.0  2.0  3.00  22.0
PI                       20.0  1.550000  0.759155  1.0  1.0  1.0  2.00   3.0
PR                      196.0  2.515306  2.576973  1.0  1.0  1.0  3.00  16.0
RJ                       61.0  3.147541  3.037741  1.0  1.0  2.0  4.00  19.0
RN                       19.0  1.736842  1.326738  1.0  1.0  1.0  2.50   6.0
RO                       16.0  2.812500  3.250000  1.0  1.0  1.0  3.25  13.0
RR                        3.0  2.000000  1.000000  1.0  1.5  2.0  2.50   3.0
RS                      195.0  4.410256  7.815257  1.0  1.0  3.0  4.00  67.0
SC                       87.0  3.402299  4.183188  1.0  1.0  1.0  3.00  20.0
SE                       20.0  1.250000  0.716350  1.0  1.0  1.0  1.00   4.0
SP                      534.0  3.361423  4.788049  1.0  1.0  2.0  4.00  47.0
TO                       18.0  1.833333  1.617914  1.0  1.0  1.0  2.00   7.0

         bolsa_integral_cotas             ...   nota_parcial_ampla          \
                        count      mean   ...                  75%     max
uf_busca                                  ...
AC                        7.0  1.428571   ...              578.775  585.72
AL                       17.0  3.294118   ...              570.115  574.42
AM                       20.0  4.300000   ...              559.680  582.26
AP                       10.0  3.700000   ...              604.580  627.40
BA                      142.0  2.640845   ...              554.440  611.48
CE                       59.0  2.423729   ...              596.250  642.78
DF                       52.0  1.826923   ...              573.200  619.70
ES                       60.0  1.833333   ...              571.180  682.36
GO                       82.0  1.890244   ...              559.780  602.18
MA                       40.0  3.475000   ...              555.220  610.46
MG                      255.0  1.886275   ...              587.315  655.32
MS                       54.0  1.703704   ...              567.760  636.70
MT                       54.0  1.500000   ...              571.630  617.86
PA                       69.0  3.536232   ...              562.860  605.16
PB                       35.0  2.685714   ...              553.120  561.96
PE                       82.0  3.585366   ...              563.720  629.88
PI                       30.0  2.833333   ...              563.730  573.20
PR                      196.0  0.785714   ...              568.820  636.68
RJ                       98.0  2.183673   ...              617.850  634.06
RN                       30.0  1.933333   ...              574.420  625.60
RO                       26.0  2.346154   ...              578.255  607.40
RR                        5.0  4.400000   ...              562.960  562.96
RS                      195.0  0.343590   ...              568.420  664.60
SC                       87.0  0.310345   ...              558.855  616.62
SE                       27.0  1.851852   ...              538.950  568.60
SP                      534.0  1.436330   ...              563.085  634.56
TO                       22.0  2.818182   ...              555.760  585.74

         nota_parcial_cotas                                                  \
                      count        mean        std     min      25%     50%
uf_busca
AC                      2.0  560.430000   7.283200  555.28  557.855  560.43
AL                      3.0  556.133333  14.658790  540.26  549.620  558.98
AM                      0.0         NaN        NaN     NaN      NaN     NaN
AP                      0.0         NaN        NaN     NaN      NaN     NaN
BA                     29.0  492.525517  44.928385  450.00  450.000  480.56
CE                     11.0  584.058182  13.050819  569.42  573.110  581.52
DF                     18.0  508.292222  53.641813  450.00  450.000  507.59
ES                     16.0  537.328750  42.358595  450.00  527.115  554.83
GO                     15.0  499.234667  42.211767  450.00  453.680  501.74
MA                     12.0  533.963333  33.916630  450.60  520.470  537.27
MG                     36.0  531.824444  47.191839  450.00  498.425  539.27
MS                     11.0  499.841818  50.492609  450.00  450.000  491.50
MT                     15.0  497.385333  38.452761  450.00  455.110  502.38
PA                      4.0  539.800000  19.228389  528.42  530.355  531.10
PB                      3.0  557.740000   7.279643  552.98  553.550  554.12
PE                      3.0  544.780000  21.861757  520.46  535.770  551.08
PI                      5.0  524.876000  31.396119  499.14  499.780  509.54
PR                     78.0  487.859231  41.019334  450.00  450.000  474.24
RJ                      8.0  582.647500  37.657520  523.86  566.905  577.15
RN                      9.0  541.700000  40.475651  474.54  521.440  553.02
RO                      7.0  533.025714  43.566462  450.00  519.220  535.32
RR                      0.0         NaN        NaN     NaN      NaN     NaN
RS                     12.0  488.753333  45.263139  450.00  450.000  476.97
SC                      3.0  450.000000   0.000000  450.00  450.000  450.00
SE                      1.0  544.300000        NaN  544.30  544.300  544.30
SP                     78.0  502.522051  45.892413  450.00  454.360  498.01
TO                      2.0  535.900000   1.131371  535.10  535.500  535.90


              75%     max
uf_busca
AC        563.005  565.58
AL        564.070  569.16
AM            NaN     NaN
AP            NaN     NaN
BA        534.220  567.72
CE        592.760  605.24
DF        557.270  594.34
ES        560.930  591.26
GO        540.860  559.00
MA        551.480  575.48
MG        568.380  634.02
MS        533.280  596.28
MT        535.710  543.26
PA        540.545  568.58
PB        560.120  566.12
PE        556.940  562.80
PI        547.320  568.60
PR        517.965  583.94
RJ        595.400  655.32
RN        567.060  594.08
RO        564.830  577.76
RR            NaN     NaN
RS        508.340  576.88
SC        450.000  450.00
SE        544.300  544.30
SP        532.845  641.18
TO        536.300  536.70

[27 rows x 72 columns]